/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("VarListListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheVarListList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheVarListList.onFilterBar().iCheckFilterField("Request Number");
            Then.onTheVarListList.onFilterBar().iCheckFilterField("Visit Type");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheVarListList.onTable().iCheckCreate({ visible: true });
            // Then.ontheVarListList.onTable().iPressCreate();
            // Then.ontheVarListList.onTable().iPressDelete();
            Then.onTheVarListList.onTable().iCheckDelete({ visible: true });
            // Then.onTheVarListList.onTable().iPressAction("Copy Request");
            Then.onTheVarListList.onTable().iCheckAction("Copy Request", { enabled: false });
            Then.onTheVarListList.onTable().iCheckColumns(8, {"ReqNum":{"header":"Request Number"},"Type":{"header":"Visit Type"},"MeansTrans":{"header":"Means of Transport"},"Begda":{"header":"Start Date"},"Endda":{"header":"End Date"},"Status":{"header":"Request Status"},"VendorName":{"header":"Vendor Name"},"ViewPDFText":{"header":"View Request Form"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheVarListList.onFilterBar().iExecuteSearch();
            
            Then.onTheVarListList.onTable().iCheckRows();

            When.onTheVarListList.onTable().iPressRow(0);
            Then.onTheVarListObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});